# Generated by Django 5.1.4 on 2025-04-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('country_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('country_description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='country_videos/')),
                ('study_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
