# Generated by Django 5.1.4 on 2025-04-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masacoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyAbroad',
            new_name='AbroadStudies',
        ),
    ]
