# Generated by Django 5.1.4 on 2025-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masacoapp', '0002_rename_studyabroad_abroadstudies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('classes', models.CharField(blank=True, max_length=100, null=True)),
                ('small_description', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_brochure', models.FileField(blank=True, null=True, upload_to='course_brochures/')),
                ('study_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
