# Generated by Django 5.1.4 on 2025-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masacoapp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_months', models.PositiveIntegerField(help_text='Duration in months')),
                ('total_classes', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='coaching_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
