# Generated by Django 5.1.4 on 2025-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masacoapp', '0005_coachingprogram_coaching_brochure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingprogram',
            name='coaching_video',
            field=models.FileField(blank=True, null=True, upload_to='coaching_videos/'),
        ),
    ]
