# Generated by Django 5.1.4 on 2025-05-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masacoapp', '0006_coachingprogram_coaching_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('coaching_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='masacoapp.coachingprogram')),
            ],
        ),
    ]
