# Generated by Django 5.1.4 on 2025-05-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masacoapp', '0009_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadstudies',
            name='country_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
